# Generated by Django 5.2.17 on 2026-10-04 15:23

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('supplier_code', models.CharField(max_length=50, unique=True, verbose_name='Mã nhà cung cấp')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Tên nhà cung cấp')),
                ('tax_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã số thuế')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'nhà cung cấp',
                'verbose_name_plural': 'Danh mục nhà cung cấp',
                'db_table': 'Suppliers',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('supplier_code', models.CharField(max_length=50, verbose_name='Mã nhà cung cấp')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Tên nhà cung cấp')),
                ('tax_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã số thuế')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='suppliers.supplier')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['-updated_at', 'id'], name='Suppliers_updated_d49ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_code'], name='Suppliers_supplie_f89ae0_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='supplier',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "suppliers_supplierevent" ("address", "created_at", "created_by_id", "deleted_at", "description", "email", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "supplier_code", "supplier_name", "tax_code", "updated_at", "updated_by_id") VALUES (NEW."address", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."email", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."supplier_code", NEW."supplier_name", NEW."tax_code", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='352a90acd61ca92fcc5aa1e93da952c3dcb0f376', operation='INSERT', pgid='pgtrigger_insert_insert_2612f', table='Suppliers', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='supplier',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "suppliers_supplierevent" ("address", "created_at", "created_by_id", "deleted_at", "description", "email", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "supplier_code", "supplier_name", "tax_code", "updated_at", "updated_by_id") VALUES (NEW."address", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."email", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."supplier_code", NEW."supplier_name", NEW."tax_code", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='2a52ef4bde95697c87601f5fc9360b653afd51dd', operation='UPDATE', pgid='pgtrigger_update_update_835e2', table='Suppliers', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='supplier',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "suppliers_supplierevent" ("address", "created_at", "created_by_id", "deleted_at", "description", "email", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "supplier_code", "supplier_name", "tax_code", "updated_at", "updated_by_id") VALUES (OLD."address", OLD."created_at", OLD."created_by_id", OLD."deleted_at", OLD."description", OLD."email", OLD."id", OLD."is_active", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone", OLD."supplier_code", OLD."supplier_name", OLD."tax_code", OLD."updated_at", OLD."updated_by_id"); RETURN NULL;', hash='4699c8c2743898a36c6418cd5b1dd30e9653f29d', operation='DELETE', pgid='pgtrigger_delete_delete_5b261', table='Suppliers', when='AFTER')),
        ),
    ]
