# Generated by Django 5.1.15 on 2026-09-04 12:29

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasureEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('code', models.CharField(max_length=20, verbose_name='Mã ĐVT')),
                ('name', models.CharField(max_length=100, verbose_name='Tên ĐVT')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unitofmeasure',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "master_data_unitofmeasureevent" ("code", "created_at", "created_by_id", "deleted_at", "description", "id", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (NEW."code", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."id", NEW."is_active", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='223391ac2ffbfe3df07fc6089565e0df1974b11b', operation='INSERT', pgid='pgtrigger_insert_insert_450fb', table='UnitsOfMeasure', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unitofmeasure',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "master_data_unitofmeasureevent" ("code", "created_at", "created_by_id", "deleted_at", "description", "id", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (NEW."code", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."id", NEW."is_active", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='ed90fa4993462d46c307abb41ec5c6eaf7bb6dd8', operation='UPDATE', pgid='pgtrigger_update_update_46843', table='UnitsOfMeasure', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unitofmeasure',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "master_data_unitofmeasureevent" ("code", "created_at", "created_by_id", "deleted_at", "description", "id", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (OLD."code", OLD."created_at", OLD."created_by_id", OLD."deleted_at", OLD."description", OLD."id", OLD."is_active", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at", OLD."updated_by_id"); RETURN NULL;', hash='6ab9106e535a63d9d2035136aa0771740057a1dc', operation='DELETE', pgid='pgtrigger_delete_delete_6d7b5', table='UnitsOfMeasure', when='AFTER')),
        ),
        migrations.AddField(
            model_name='unitofmeasureevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='unitofmeasureevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='unitofmeasureevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='master_data.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='unitofmeasureevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất'),
        ),
    ]
