# Generated by Django 5.1.15 on 2026-09-23 12:45

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_unitofmeasureevent_unitofmeasure_insert_insert_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã nhóm NVL')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm NVL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='master_data.materialcategory', verbose_name='Nhóm cha')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'Nhóm nguyên vật liệu',
                'verbose_name_plural': 'Danh mục Nhóm nguyên vật liệu',
                'db_table': 'MaterialCategories',
                'ordering': ['sort_order', '-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategoryEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('code', models.CharField(max_length=50, verbose_name='Mã nhóm NVL')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm NVL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='master_data.materialcategory', verbose_name='Nhóm cha')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='master_data.materialcategory')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='materialcategory',
            index=models.Index(fields=['sort_order', '-updated_at', 'id'], name='MaterialCat_sort_or_c7b0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='materialcategory',
            index=models.Index(fields=['code'], name='MaterialCat_code_c4429d_idx'),
        ),
        migrations.AddIndex(
            model_name='materialcategory',
            index=models.Index(fields=['parent', 'sort_order'], name='MaterialCat_parent__687e46_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='materialcategory',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "master_data_materialcategoryevent" ("code", "created_at", "created_by_id", "deleted_at", "description", "id", "is_active", "name", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order", "updated_at", "updated_by_id") VALUES (NEW."code", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."id", NEW."is_active", NEW."name", NEW."parent_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sort_order", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='a5fba1fc3b40bae4bbfaad58eda69a624d84e9fb', operation='INSERT', pgid='pgtrigger_insert_insert_4be66', table='MaterialCategories', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='materialcategory',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "master_data_materialcategoryevent" ("code", "created_at", "created_by_id", "deleted_at", "description", "id", "is_active", "name", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order", "updated_at", "updated_by_id") VALUES (NEW."code", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."id", NEW."is_active", NEW."name", NEW."parent_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sort_order", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='d6638d0cc745b8561c401190779482ecf8b9bc00', operation='UPDATE', pgid='pgtrigger_update_update_cd87b', table='MaterialCategories', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='materialcategory',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "master_data_materialcategoryevent" ("code", "created_at", "created_by_id", "deleted_at", "description", "id", "is_active", "name", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order", "updated_at", "updated_by_id") VALUES (OLD."code", OLD."created_at", OLD."created_by_id", OLD."deleted_at", OLD."description", OLD."id", OLD."is_active", OLD."name", OLD."parent_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sort_order", OLD."updated_at", OLD."updated_by_id"); RETURN NULL;', hash='d2f355f07614facd16dcccc9dc49e4be344290fe', operation='DELETE', pgid='pgtrigger_delete_delete_45bda', table='MaterialCategories', when='AFTER')),
        ),
    ]
