# Generated by Django 5.1.15 on 2026-09-24 12:08

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_materialcategory_materialcategoryevent_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('material_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Mã NVL')),
                ('material_name', models.CharField(db_index=True, max_length=255, verbose_name='Tên NVL')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Đường dẫn ảnh đại diện / bản vẽ mặt cắt')),
                ('base_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='master_data.unitofmeasure', verbose_name='ĐVT lưu kho')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='master_data.materialcategory', verbose_name='Nhóm NVL')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'Nguyên vật liệu',
                'verbose_name_plural': 'Danh mục Nguyên vật liệu',
                'db_table': 'Materials',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MetalMaterialSpec',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metal_spec', serialize=False, to='master_data.material', verbose_name='Vật tư kim loại')),
                ('profile_shape', models.CharField(choices=[('ROUND_PIPE', 'Ống tròn rỗng (P)'), ('SOLID_ROUND', 'Tròn đặc (D)'), ('SQUARE_TUBE', 'Hộp vuông rỗng (V)'), ('SOLID_SQUARE', 'Vuông đặc (V...D)'), ('RECT_TUBE', 'Hộp chữ nhật rỗng (CN)'), ('OVAL_PIPE', 'Oval / Elip rỗng (ELIP)'), ('FLAT_BAR', 'La / Dẹt đặc (L)'), ('ANGLE_V', 'Thép V / Nhôm V'), ('SHEET', 'Nhôm / Sắt tấm (T)'), ('SPECIAL_MOLD', 'Khuôn định hình đặc biệt (SP)')], default='RECT_TUBE', max_length=50, verbose_name='Hình dạng mặt cắt')),
                ('outer_dimension_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kích thước 1 (Ø/a/w) mm')),
                ('outer_dimension_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kích thước 2 (b/h) mm')),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Độ dày thành t mm')),
                ('standard_bar_length', models.DecimalField(decimal_places=2, default=6000.0, max_digits=10, verbose_name='Chiều dài thanh tiêu chuẩn mm')),
                ('end_trim_loss', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Hao hụt đầu mẩu bavia mm')),
                ('saw_kerf_loss', models.DecimalField(decimal_places=2, default=3.0, max_digits=10, verbose_name='Bề dày mạch cưa mm')),
                ('weight_per_meter_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Định lượng kg/m thực tế')),
                ('mold_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Mã khuôn ép NCC')),
                ('features', models.CharField(blank=True, default='', max_length=50, verbose_name='Ký hiệu phụ (Gân/Gờ...)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'Quy cách phôi kim loại',
                'verbose_name_plural': 'Bảng Quy cách phôi kim loại',
                'db_table': 'MetalMaterialSpecs',
                'ordering': ['-updated_at', 'material_id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('material_code', models.CharField(max_length=50, verbose_name='Mã NVL')),
                ('material_name', models.CharField(max_length=255, verbose_name='Tên NVL')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Đường dẫn ảnh đại diện / bản vẽ mặt cắt')),
                ('base_uom', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='master_data.unitofmeasure', verbose_name='ĐVT lưu kho')),
                ('category', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='master_data.materialcategory', verbose_name='Nhóm NVL')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='master_data.material')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetalMaterialSpecEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('profile_shape', models.CharField(choices=[('ROUND_PIPE', 'Ống tròn rỗng (P)'), ('SOLID_ROUND', 'Tròn đặc (D)'), ('SQUARE_TUBE', 'Hộp vuông rỗng (V)'), ('SOLID_SQUARE', 'Vuông đặc (V...D)'), ('RECT_TUBE', 'Hộp chữ nhật rỗng (CN)'), ('OVAL_PIPE', 'Oval / Elip rỗng (ELIP)'), ('FLAT_BAR', 'La / Dẹt đặc (L)'), ('ANGLE_V', 'Thép V / Nhôm V'), ('SHEET', 'Nhôm / Sắt tấm (T)'), ('SPECIAL_MOLD', 'Khuôn định hình đặc biệt (SP)')], default='RECT_TUBE', max_length=50, verbose_name='Hình dạng mặt cắt')),
                ('outer_dimension_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kích thước 1 (Ø/a/w) mm')),
                ('outer_dimension_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kích thước 2 (b/h) mm')),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Độ dày thành t mm')),
                ('standard_bar_length', models.DecimalField(decimal_places=2, default=6000.0, max_digits=10, verbose_name='Chiều dài thanh tiêu chuẩn mm')),
                ('end_trim_loss', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Hao hụt đầu mẩu bavia mm')),
                ('saw_kerf_loss', models.DecimalField(decimal_places=2, default=3.0, max_digits=10, verbose_name='Bề dày mạch cưa mm')),
                ('weight_per_meter_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Định lượng kg/m thực tế')),
                ('mold_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Mã khuôn ép NCC')),
                ('features', models.CharField(blank=True, default='', max_length=50, verbose_name='Ký hiệu phụ (Gân/Gờ...)')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('material', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', serialize=False, to='master_data.material', verbose_name='Vật tư kim loại')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='master_data.metalmaterialspec')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['-updated_at', 'id'], name='Materials_updated_35eba5_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['category', 'material_code'], name='Materials_categor_661539_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['material_code'], name='Materials_materia_22bdc5_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['material_name'], name='Materials_materia_c171c2_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='material',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "master_data_materialevent" ("base_uom_id", "category_id", "created_at", "created_by_id", "deleted_at", "description", "id", "image_url", "is_active", "material_code", "material_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (NEW."base_uom_id", NEW."category_id", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."id", NEW."image_url", NEW."is_active", NEW."material_code", NEW."material_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='44a6df1de9524e2ea79e4a6497f448f5ff756e91', operation='INSERT', pgid='pgtrigger_insert_insert_0d968', table='Materials', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='material',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "master_data_materialevent" ("base_uom_id", "category_id", "created_at", "created_by_id", "deleted_at", "description", "id", "image_url", "is_active", "material_code", "material_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (NEW."base_uom_id", NEW."category_id", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."id", NEW."image_url", NEW."is_active", NEW."material_code", NEW."material_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='a250a3c79de5fc42d3a55224e6b8e8e10dc5b352', operation='UPDATE', pgid='pgtrigger_update_update_f33be', table='Materials', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='material',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "master_data_materialevent" ("base_uom_id", "category_id", "created_at", "created_by_id", "deleted_at", "description", "id", "image_url", "is_active", "material_code", "material_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (OLD."base_uom_id", OLD."category_id", OLD."created_at", OLD."created_by_id", OLD."deleted_at", OLD."description", OLD."id", OLD."image_url", OLD."is_active", OLD."material_code", OLD."material_name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at", OLD."updated_by_id"); RETURN NULL;', hash='98c59b03e27bb45682141c2102fbe4b12f2574b2', operation='DELETE', pgid='pgtrigger_delete_delete_8d7bf', table='Materials', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='metalmaterialspec',
            index=models.Index(fields=['-updated_at', 'material_id'], name='MetalMateri_updated_6632d5_idx'),
        ),
        migrations.AddIndex(
            model_name='metalmaterialspec',
            index=models.Index(fields=['profile_shape'], name='MetalMateri_profile_691e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='metalmaterialspec',
            index=models.Index(fields=['mold_code'], name='MetalMateri_mold_co_80f6dd_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='metalmaterialspec',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "master_data_metalmaterialspecevent" ("created_at", "created_by_id", "deleted_at", "description", "end_trim_loss", "features", "is_active", "material_id", "mold_code", "outer_dimension_1", "outer_dimension_2", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_shape", "saw_kerf_loss", "standard_bar_length", "thickness", "updated_at", "updated_by_id", "weight_per_meter_kg") VALUES (NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."end_trim_loss", NEW."features", NEW."is_active", NEW."material_id", NEW."mold_code", NEW."outer_dimension_1", NEW."outer_dimension_2", _pgh_attach_context(), NOW(), \'insert\', NEW."material_id", NEW."profile_shape", NEW."saw_kerf_loss", NEW."standard_bar_length", NEW."thickness", NEW."updated_at", NEW."updated_by_id", NEW."weight_per_meter_kg"); RETURN NULL;', hash='b1c307ab3c39d82b4e080fa2a62b6f1e7135e020', operation='INSERT', pgid='pgtrigger_insert_insert_2e42f', table='MetalMaterialSpecs', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='metalmaterialspec',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "master_data_metalmaterialspecevent" ("created_at", "created_by_id", "deleted_at", "description", "end_trim_loss", "features", "is_active", "material_id", "mold_code", "outer_dimension_1", "outer_dimension_2", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_shape", "saw_kerf_loss", "standard_bar_length", "thickness", "updated_at", "updated_by_id", "weight_per_meter_kg") VALUES (NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."end_trim_loss", NEW."features", NEW."is_active", NEW."material_id", NEW."mold_code", NEW."outer_dimension_1", NEW."outer_dimension_2", _pgh_attach_context(), NOW(), \'update\', NEW."material_id", NEW."profile_shape", NEW."saw_kerf_loss", NEW."standard_bar_length", NEW."thickness", NEW."updated_at", NEW."updated_by_id", NEW."weight_per_meter_kg"); RETURN NULL;', hash='8cef477a88e71f89ce8098e15ba471f2e507a016', operation='UPDATE', pgid='pgtrigger_update_update_68ad8', table='MetalMaterialSpecs', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='metalmaterialspec',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "master_data_metalmaterialspecevent" ("created_at", "created_by_id", "deleted_at", "description", "end_trim_loss", "features", "is_active", "material_id", "mold_code", "outer_dimension_1", "outer_dimension_2", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "profile_shape", "saw_kerf_loss", "standard_bar_length", "thickness", "updated_at", "updated_by_id", "weight_per_meter_kg") VALUES (OLD."created_at", OLD."created_by_id", OLD."deleted_at", OLD."description", OLD."end_trim_loss", OLD."features", OLD."is_active", OLD."material_id", OLD."mold_code", OLD."outer_dimension_1", OLD."outer_dimension_2", _pgh_attach_context(), NOW(), \'delete\', OLD."material_id", OLD."profile_shape", OLD."saw_kerf_loss", OLD."standard_bar_length", OLD."thickness", OLD."updated_at", OLD."updated_by_id", OLD."weight_per_meter_kg"); RETURN NULL;', hash='862aa372ac5fde4290b3ad72d9d55659f9d77227', operation='DELETE', pgid='pgtrigger_delete_delete_81a7c', table='MetalMaterialSpecs', when='AFTER')),
        ),
    ]
