# Generated by Django 5.2.17 on 2026-10-04 15:04

import django.core.validators
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('customer_code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Mã khách hàng chỉ gồm chữ in hoa không dấu, số và dấu gạch dưới (dùng trong SKU).')], verbose_name='Mã khách hàng')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quốc gia / Thị trường')),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Logo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'khách hàng',
                'verbose_name_plural': 'Danh mục khách hàng',
                'db_table': 'Customers',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('customer_code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Mã khách hàng chỉ gồm chữ in hoa không dấu, số và dấu gạch dưới (dùng trong SKU).')], verbose_name='Mã khách hàng')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quốc gia / Thị trường')),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Logo')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-updated_at', 'id'], name='Customers_updated_5b2032_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_code'], name='Customers_custome_21c161_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='customer',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "customers_customerevent" ("country", "created_at", "created_by_id", "customer_code", "customer_name", "deleted_at", "description", "id", "is_active", "logo_url", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (NEW."country", NEW."created_at", NEW."created_by_id", NEW."customer_code", NEW."customer_name", NEW."deleted_at", NEW."description", NEW."id", NEW."is_active", NEW."logo_url", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='5479f3da442b302575e78d4c01d1542a220708d0', operation='INSERT', pgid='pgtrigger_insert_insert_a36e0', table='Customers', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='customer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "customers_customerevent" ("country", "created_at", "created_by_id", "customer_code", "customer_name", "deleted_at", "description", "id", "is_active", "logo_url", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (NEW."country", NEW."created_at", NEW."created_by_id", NEW."customer_code", NEW."customer_name", NEW."deleted_at", NEW."description", NEW."id", NEW."is_active", NEW."logo_url", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='de70d0f32c26be11414a1f140b7ca470b5152f29', operation='UPDATE', pgid='pgtrigger_update_update_ca86d', table='Customers', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='customer',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "customers_customerevent" ("country", "created_at", "created_by_id", "customer_code", "customer_name", "deleted_at", "description", "id", "is_active", "logo_url", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (OLD."country", OLD."created_at", OLD."created_by_id", OLD."customer_code", OLD."customer_name", OLD."deleted_at", OLD."description", OLD."id", OLD."is_active", OLD."logo_url", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at", OLD."updated_by_id"); RETURN NULL;', hash='7a4768a26fece120799fcbfbee4b6637b14ea123', operation='DELETE', pgid='pgtrigger_delete_delete_939ca', table='Customers', when='AFTER')),
        ),
    ]
