# Generated by Django 5.1.15 on 2026-09-05 12:27

import apps.core.models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('entity_type', models.CharField(help_text='VD: USER, PRODUCT_BASE, PRODUCT_VARIANT, MATERIAL, WORK_ORDER...', max_length=50, verbose_name='Loại thực thể')),
                ('entity_id', models.IntegerField(verbose_name='Mã Id của thực thể đính kèm')),
                ('file', models.FileField(max_length=500, upload_to=apps.core.models.attachment_upload_path, verbose_name='Tệp đính kèm')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên gốc của tệp')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dung lượng tệp (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Định dạng MIME')),
                ('file_category', models.CharField(choices=[('DOCUMENT', 'Tài liệu chung'), ('IMAGE', 'Hình ảnh / Bản chụp'), ('CAD_DRAWING', 'Bản vẽ kỹ thuật CAD / DWG'), ('SPEC_SHEET', 'Bản thông số kỹ thuật'), ('CONTRACT', 'Hợp đồng / Đơn vị chứng từ'), ('OTHER', 'Khác')], default='DOCUMENT', max_length=50, verbose_name='Phân loại tệp')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'Tệp đính kèm',
                'verbose_name_plural': 'Danh mục Tệp đính kèm',
                'db_table': 'Attachments',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('entity_type', models.CharField(help_text='VD: USER, PRODUCT_BASE, PRODUCT_VARIANT, MATERIAL, WORK_ORDER...', max_length=50, verbose_name='Loại thực thể')),
                ('entity_id', models.IntegerField(verbose_name='Mã Id của thực thể đính kèm')),
                ('file', models.FileField(max_length=500, upload_to=apps.core.models.attachment_upload_path, verbose_name='Tệp đính kèm')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên gốc của tệp')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dung lượng tệp (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Định dạng MIME')),
                ('file_category', models.CharField(choices=[('DOCUMENT', 'Tài liệu chung'), ('IMAGE', 'Hình ảnh / Bản chụp'), ('CAD_DRAWING', 'Bản vẽ kỹ thuật CAD / DWG'), ('SPEC_SHEET', 'Bản thông số kỹ thuật'), ('CONTRACT', 'Hợp đồng / Đơn vị chứng từ'), ('OTHER', 'Khác')], default='DOCUMENT', max_length=50, verbose_name='Phân loại tệp')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.attachment')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['-updated_at', 'id'], name='Attachments_updated_eec423_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['entity_type', 'entity_id'], name='Attachments_entity__e879ce_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['file_category'], name='Attachments_file_ca_03bafb_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attachment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_attachmentevent" ("created_at", "created_by_id", "deleted_at", "description", "entity_id", "entity_type", "file", "file_category", "file_name", "file_size", "id", "is_active", "mime_type", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."entity_id", NEW."entity_type", NEW."file", NEW."file_category", NEW."file_name", NEW."file_size", NEW."id", NEW."is_active", NEW."mime_type", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='0b6f9f911b7b18fab535f3037448738d9355112b', operation='INSERT', pgid='pgtrigger_insert_insert_31589', table='Attachments', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attachment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_attachmentevent" ("created_at", "created_by_id", "deleted_at", "description", "entity_id", "entity_type", "file", "file_category", "file_name", "file_size", "id", "is_active", "mime_type", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."entity_id", NEW."entity_type", NEW."file", NEW."file_category", NEW."file_name", NEW."file_size", NEW."id", NEW."is_active", NEW."mime_type", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='3e487db315b7166ab254a32a47c5ec832372fc3b', operation='UPDATE', pgid='pgtrigger_update_update_b73a5', table='Attachments', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attachment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_attachmentevent" ("created_at", "created_by_id", "deleted_at", "description", "entity_id", "entity_type", "file", "file_category", "file_name", "file_size", "id", "is_active", "mime_type", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (OLD."created_at", OLD."created_by_id", OLD."deleted_at", OLD."description", OLD."entity_id", OLD."entity_type", OLD."file", OLD."file_category", OLD."file_name", OLD."file_size", OLD."id", OLD."is_active", OLD."mime_type", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at", OLD."updated_by_id"); RETURN NULL;', hash='8978933d1ad0205d9e5ec85cc584af94d9ea1693', operation='DELETE', pgid='pgtrigger_delete_delete_5704f', table='Attachments', when='AFTER')),
        ),
    ]
