# Generated by Django 5.1.15 on 2026-09-10 12:14

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransferJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('job_type', models.CharField(choices=[('EXPORT_EXCEL', 'Xuất Excel (.xlsx)'), ('EXPORT_CSV', 'Xuất CSV (.csv)'), ('IMPORT_EXCEL', 'Nhập dữ liệu từ Excel')], default='EXPORT_EXCEL', max_length=30, verbose_name='Loại tác vụ')),
                ('entity_type', models.CharField(help_text='VD: USER, PRODUCT_BASE, MATERIAL, CUSTOMER...', max_length=50, verbose_name='Tên loại thực thể')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý trong hàng đợi'), ('PROCESSING', 'Đang xử lý dữ liệu'), ('COMPLETED', 'Đã hoàn tất'), ('FAILED', 'Thất bại'), ('CANCELLED', 'Đã hủy bỏ')], default='PENDING', max_length=20, verbose_name='Trạng thái thực thi')),
                ('progress', models.IntegerField(default=0, verbose_name='Tiến độ hoàn thành (%)')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Tổng số dòng cần xử lý')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='Số dòng đã xử lý xong')),
                ('file_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn file kết quả')),
                ('error_file_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn file tổng hợp dòng lỗi')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Chi tiết lỗi nếu thất bại')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='Tham số truy vấn (scope, filters, columns)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm bắt đầu thực thi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hoàn tất')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'Tác vụ truyền dữ liệu',
                'verbose_name_plural': 'Danh mục Tác vụ truyền dữ liệu (Async Jobs)',
                'db_table': 'DataTransferJobs',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DataTransferJobEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('job_type', models.CharField(choices=[('EXPORT_EXCEL', 'Xuất Excel (.xlsx)'), ('EXPORT_CSV', 'Xuất CSV (.csv)'), ('IMPORT_EXCEL', 'Nhập dữ liệu từ Excel')], default='EXPORT_EXCEL', max_length=30, verbose_name='Loại tác vụ')),
                ('entity_type', models.CharField(help_text='VD: USER, PRODUCT_BASE, MATERIAL, CUSTOMER...', max_length=50, verbose_name='Tên loại thực thể')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý trong hàng đợi'), ('PROCESSING', 'Đang xử lý dữ liệu'), ('COMPLETED', 'Đã hoàn tất'), ('FAILED', 'Thất bại'), ('CANCELLED', 'Đã hủy bỏ')], default='PENDING', max_length=20, verbose_name='Trạng thái thực thi')),
                ('progress', models.IntegerField(default=0, verbose_name='Tiến độ hoàn thành (%)')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Tổng số dòng cần xử lý')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='Số dòng đã xử lý xong')),
                ('file_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn file kết quả')),
                ('error_file_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn file tổng hợp dòng lỗi')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Chi tiết lỗi nếu thất bại')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='Tham số truy vấn (scope, filters, columns)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm bắt đầu thực thi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hoàn tất')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.datatransferjob')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='datatransferjob',
            index=models.Index(fields=['-updated_at', 'id'], name='DataTransfe_updated_3ba9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='datatransferjob',
            index=models.Index(fields=['created_by', 'status'], name='DataTransfe_created_d44aba_idx'),
        ),
        migrations.AddIndex(
            model_name='datatransferjob',
            index=models.Index(fields=['job_type', 'status'], name='DataTransfe_job_typ_b0f9c2_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='datatransferjob',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_datatransferjobevent" ("completed_at", "created_at", "created_by_id", "deleted_at", "description", "entity_type", "error_file_url", "error_message", "file_url", "id", "is_active", "job_type", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "processed_rows", "progress", "query_params", "started_at", "status", "total_rows", "updated_at", "updated_by_id") VALUES (NEW."completed_at", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."entity_type", NEW."error_file_url", NEW."error_message", NEW."file_url", NEW."id", NEW."is_active", NEW."job_type", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."processed_rows", NEW."progress", NEW."query_params", NEW."started_at", NEW."status", NEW."total_rows", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='35a9de3fde4014194e863e323001357dc88ede9e', operation='INSERT', pgid='pgtrigger_insert_insert_aec53', table='DataTransferJobs', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='datatransferjob',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_datatransferjobevent" ("completed_at", "created_at", "created_by_id", "deleted_at", "description", "entity_type", "error_file_url", "error_message", "file_url", "id", "is_active", "job_type", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "processed_rows", "progress", "query_params", "started_at", "status", "total_rows", "updated_at", "updated_by_id") VALUES (NEW."completed_at", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."entity_type", NEW."error_file_url", NEW."error_message", NEW."file_url", NEW."id", NEW."is_active", NEW."job_type", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."processed_rows", NEW."progress", NEW."query_params", NEW."started_at", NEW."status", NEW."total_rows", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='7cc4a6230298d31a3d57e8137981cf80c2e5afbe', operation='UPDATE', pgid='pgtrigger_update_update_0449b', table='DataTransferJobs', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='datatransferjob',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_datatransferjobevent" ("completed_at", "created_at", "created_by_id", "deleted_at", "description", "entity_type", "error_file_url", "error_message", "file_url", "id", "is_active", "job_type", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "processed_rows", "progress", "query_params", "started_at", "status", "total_rows", "updated_at", "updated_by_id") VALUES (OLD."completed_at", OLD."created_at", OLD."created_by_id", OLD."deleted_at", OLD."description", OLD."entity_type", OLD."error_file_url", OLD."error_message", OLD."file_url", OLD."id", OLD."is_active", OLD."job_type", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."processed_rows", OLD."progress", OLD."query_params", OLD."started_at", OLD."status", OLD."total_rows", OLD."updated_at", OLD."updated_by_id"); RETURN NULL;', hash='2b06e0af759d5985af6aa0476a553cf5ac12c967', operation='DELETE', pgid='pgtrigger_delete_delete_712f1', table='DataTransferJobs', when='AFTER')),
        ),
    ]
