# Generated by Django 5.2.17 on 2026-09-26 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datatransferjob_datatransferjobevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('level', models.CharField(choices=[('INFO', 'Thông tin'), ('SUCCESS', 'Thành công'), ('WARNING', 'Cảnh báo'), ('ERROR', 'Lỗi')], default='INFO', max_length=20, verbose_name='Mức độ')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn khi bấm vào')),
                ('source_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nguồn phát sinh')),
                ('source_id', models.BigIntegerField(blank=True, null=True, verbose_name='Mã bản ghi nguồn')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm đọc')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'db_table': 'Notifications',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='Notificatio_recipie_1681a5_idx'), models.Index(fields=['-created_at'], name='Notificatio_created_50868f_idx')],
            },
        ),
    ]
