# Generated by Django 5.2.17 on 2026-09-26 19:49

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notifications'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('app_name', models.CharField(max_length=100, verbose_name='Tên ứng dụng')),
                ('app_badge', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nhãn phụ')),
                ('tagline', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dòng mô tả ngắn')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đơn vị sở hữu')),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Logo')),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50, verbose_name='Múi giờ')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD'), ('MM/DD/YYYY', 'MM/DD/YYYY')], default='DD/MM/YYYY', max_length=20, verbose_name='Định dạng ngày')),
                ('number_format', models.CharField(choices=[('INTL', 'Quốc tế (1,250.50)'), ('VN', 'Việt Nam (1.250,50)')], default='INTL', max_length=10, verbose_name='Định dạng số mặc định')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'Cấu hình hệ thống',
                'verbose_name_plural': 'Cấu hình hệ thống',
                'db_table': 'SystemSettings',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettingsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('app_name', models.CharField(max_length=100, verbose_name='Tên ứng dụng')),
                ('app_badge', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nhãn phụ')),
                ('tagline', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dòng mô tả ngắn')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đơn vị sở hữu')),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Logo')),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50, verbose_name='Múi giờ')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD'), ('MM/DD/YYYY', 'MM/DD/YYYY')], default='DD/MM/YYYY', max_length=20, verbose_name='Định dạng ngày')),
                ('number_format', models.CharField(choices=[('INTL', 'Quốc tế (1,250.50)'), ('VN', 'Việt Nam (1.250,50)')], default='INTL', max_length=10, verbose_name='Định dạng số mặc định')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.systemsettings')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='systemsettings',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_systemsettingsevent" ("app_badge", "app_name", "company_name", "created_at", "created_by_id", "date_format", "deleted_at", "description", "id", "is_active", "logo_url", "number_format", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagline", "timezone", "updated_at", "updated_by_id") VALUES (NEW."app_badge", NEW."app_name", NEW."company_name", NEW."created_at", NEW."created_by_id", NEW."date_format", NEW."deleted_at", NEW."description", NEW."id", NEW."is_active", NEW."logo_url", NEW."number_format", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tagline", NEW."timezone", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='38f49fca942228df9b34b2047ee688d32d600e0e', operation='INSERT', pgid='pgtrigger_insert_insert_33dac', table='SystemSettings', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='systemsettings',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_systemsettingsevent" ("app_badge", "app_name", "company_name", "created_at", "created_by_id", "date_format", "deleted_at", "description", "id", "is_active", "logo_url", "number_format", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagline", "timezone", "updated_at", "updated_by_id") VALUES (NEW."app_badge", NEW."app_name", NEW."company_name", NEW."created_at", NEW."created_by_id", NEW."date_format", NEW."deleted_at", NEW."description", NEW."id", NEW."is_active", NEW."logo_url", NEW."number_format", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."tagline", NEW."timezone", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='9a38c69d20448398ba02045cde15a25b3bdfdfbe', operation='UPDATE', pgid='pgtrigger_update_update_b7356', table='SystemSettings', when='AFTER')),
        ),
    ]
