# Generated by Django 5.1.15 on 2026-09-01 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-updated_at', 'id'], 'verbose_name': 'Tài khoản Người dùng', 'verbose_name_plural': 'Danh sách Tài khoản Người dùng'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú tài khoản'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Số điện thoại liên hệ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Họ và tên hiển thị'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='Users',
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(max_length=100, unique=True, verbose_name='Mã quyền hạn')),
                ('permission_name', models.CharField(max_length=255, verbose_name='Tên quyền hạn')),
                ('module', models.CharField(max_length=50, verbose_name='Thuộc phân hệ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết quyền hạn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
            ],
            options={
                'verbose_name': 'Quyền hạn chi tiết',
                'verbose_name_plural': 'Danh mục Quyền hạn chi tiết',
                'db_table': 'Permissions',
                'ordering': ['module', 'permission_code'],
                'indexes': [models.Index(fields=['module', 'permission_code'], name='Permissions_module_8cfd61_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('role_code', models.CharField(max_length=50, unique=True, verbose_name='Mã vai trò')),
                ('role_name', models.CharField(max_length=255, verbose_name='Tên hiển thị vai trò')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'Vai trò người dùng',
                'verbose_name_plural': 'Danh mục Vai trò người dùng',
                'db_table': 'Roles',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm gán quyền')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_assignments', to='authentication.permission', verbose_name='Quyền hạn')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_assignments', to='authentication.role', verbose_name='Vai trò')),
            ],
            options={
                'verbose_name': 'Phân quyền Vai trò - Quyền hạn',
                'verbose_name_plural': 'Danh sách Phân quyền Vai trò - Quyền hạn',
                'db_table': 'RolePermissions',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm gán vai trò')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Người phân quyền')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to='authentication.role', verbose_name='Vai trò')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phân quyền Người dùng - Vai trò',
                'verbose_name_plural': 'Danh sách Phân quyền Người dùng - Vai trò',
                'db_table': 'UserRoles',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='authentication.UserRole', to='authentication.role', verbose_name='Các vai trò đảm nhiệm'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['-updated_at', 'id'], name='Users_updated_f090bb_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='Users_usernam_d4a892_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='Users_email_838c41_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['-updated_at', 'id'], name='Roles_updated_3c97ff_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['role_code'], name='Roles_role_co_cc5cac_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission'], name='RolePermiss_role_id_77190d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role'], name='UserRoles_user_id_1c5273_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
