# Generated by Django 5.1.15 on 2026-09-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_options_remove_customuser_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('module_code', models.CharField(max_length=50, unique=True, verbose_name='Mã phân hệ')),
                ('module_name', models.CharField(max_length=255, verbose_name='Tên hiển thị phân hệ')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Icon Ant Design')),
                ('route_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đường dẫn Route Frontend')),
                ('parent_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã phân hệ cha')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị trên Sidebar')),
                ('is_navigation', models.BooleanField(default=True, verbose_name='Hiển thị trên Sidebar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái kích hoạt')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả phạm vi phân hệ')),
            ],
            options={
                'verbose_name': 'Cấu hình Phân hệ & Điều hướng',
                'verbose_name_plural': 'Danh mục Cấu hình Phân hệ & Điều hướng',
                'db_table': 'ModuleRegistries',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['sort_order', 'id'], name='ModuleRegis_sort_or_ce661e_idx'), models.Index(fields=['module_code'], name='ModuleRegis_module__6b2048_idx'), models.Index(fields=['parent_code'], name='ModuleRegis_parent__3abf0e_idx')],
            },
        ),
    ]
