# Generated by Django 5.1.15 on 2026-09-04 12:29

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_moduleregistry'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Họ và tên hiển thị')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Số điện thoại liên hệ')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ghi chú tài khoản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleRegistryEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('module_code', models.CharField(max_length=50, verbose_name='Mã phân hệ')),
                ('module_name', models.CharField(max_length=255, verbose_name='Tên hiển thị phân hệ')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Icon Ant Design')),
                ('route_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đường dẫn Route Frontend')),
                ('parent_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã phân hệ cha')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị trên Sidebar')),
                ('is_navigation', models.BooleanField(default=True, verbose_name='Hiển thị trên Sidebar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái kích hoạt')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả phạm vi phân hệ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('role_code', models.CharField(max_length=50, verbose_name='Mã vai trò')),
                ('role_name', models.CharField(max_length=255, verbose_name='Tên hiển thị vai trò')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='customuser',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "authentication_customuserevent" ("avatar", "created_at", "date_joined", "deleted_at", "description", "email", "first_name", "full_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "updated_at", "username") VALUES (NEW."avatar", NEW."created_at", NEW."date_joined", NEW."deleted_at", NEW."description", NEW."email", NEW."first_name", NEW."full_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."last_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."updated_at", NEW."username"); RETURN NULL;', hash='622f0038069972766973e7256c95d91671949e06', operation='INSERT', pgid='pgtrigger_insert_insert_6bdb7', table='Users', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='customuser',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."avatar" IS DISTINCT FROM (NEW."avatar") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."date_joined" IS DISTINCT FROM (NEW."date_joined") OR OLD."deleted_at" IS DISTINCT FROM (NEW."deleted_at") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."first_name" IS DISTINCT FROM (NEW."first_name") OR OLD."full_name" IS DISTINCT FROM (NEW."full_name") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."last_login" IS DISTINCT FROM (NEW."last_login") OR OLD."last_name" IS DISTINCT FROM (NEW."last_name") OR OLD."phone_number" IS DISTINCT FROM (NEW."phone_number") OR OLD."updated_at" IS DISTINCT FROM (NEW."updated_at") OR OLD."username" IS DISTINCT FROM (NEW."username"))', func='INSERT INTO "authentication_customuserevent" ("avatar", "created_at", "date_joined", "deleted_at", "description", "email", "first_name", "full_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "updated_at", "username") VALUES (NEW."avatar", NEW."created_at", NEW."date_joined", NEW."deleted_at", NEW."description", NEW."email", NEW."first_name", NEW."full_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."last_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."updated_at", NEW."username"); RETURN NULL;', hash='6ed3a4c57de208c4159583e027e3a4a5e80c65cd', operation='UPDATE', pgid='pgtrigger_update_update_4ba13', table='Users', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='customuser',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "authentication_customuserevent" ("avatar", "created_at", "date_joined", "deleted_at", "description", "email", "first_name", "full_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "updated_at", "username") VALUES (OLD."avatar", OLD."created_at", OLD."date_joined", OLD."deleted_at", OLD."description", OLD."email", OLD."first_name", OLD."full_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_login", OLD."last_name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone_number", OLD."updated_at", OLD."username"); RETURN NULL;', hash='943a1ac86ffc8f483b5da37d456f6e1293795081', operation='DELETE', pgid='pgtrigger_delete_delete_e465d', table='Users', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='moduleregistry',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "authentication_moduleregistryevent" ("created_at", "description", "icon", "id", "is_active", "is_navigation", "module_code", "module_name", "parent_code", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "route_path", "sort_order", "updated_at") VALUES (NEW."created_at", NEW."description", NEW."icon", NEW."id", NEW."is_active", NEW."is_navigation", NEW."module_code", NEW."module_name", NEW."parent_code", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."route_path", NEW."sort_order", NEW."updated_at"); RETURN NULL;', hash='b4a63469c484a540e76764592ae0901f73299b0b', operation='INSERT', pgid='pgtrigger_insert_insert_8a93c', table='ModuleRegistries', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='moduleregistry',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "authentication_moduleregistryevent" ("created_at", "description", "icon", "id", "is_active", "is_navigation", "module_code", "module_name", "parent_code", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "route_path", "sort_order", "updated_at") VALUES (NEW."created_at", NEW."description", NEW."icon", NEW."id", NEW."is_active", NEW."is_navigation", NEW."module_code", NEW."module_name", NEW."parent_code", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."route_path", NEW."sort_order", NEW."updated_at"); RETURN NULL;', hash='2f8738dacc6b1034064613433f8e762e830ec595', operation='UPDATE', pgid='pgtrigger_update_update_005a8', table='ModuleRegistries', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='moduleregistry',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "authentication_moduleregistryevent" ("created_at", "description", "icon", "id", "is_active", "is_navigation", "module_code", "module_name", "parent_code", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "route_path", "sort_order", "updated_at") VALUES (OLD."created_at", OLD."description", OLD."icon", OLD."id", OLD."is_active", OLD."is_navigation", OLD."module_code", OLD."module_name", OLD."parent_code", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."route_path", OLD."sort_order", OLD."updated_at"); RETURN NULL;', hash='647b63fc911db3899128388d0c83b48a1a98705c', operation='DELETE', pgid='pgtrigger_delete_delete_e42e5', table='ModuleRegistries', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='role',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "authentication_roleevent" ("created_at", "created_by_id", "deleted_at", "description", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_code", "role_name", "updated_at", "updated_by_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role_code", NEW."role_name", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='fdcea67f48b8f704b5fe1125bf9fdadf77902c45', operation='INSERT', pgid='pgtrigger_insert_insert_ad2fa', table='Roles', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='role',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "authentication_roleevent" ("created_at", "created_by_id", "deleted_at", "description", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_code", "role_name", "updated_at", "updated_by_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role_code", NEW."role_name", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='daa47332b4e77914c4605f40e1ac47e0ec347091', operation='UPDATE', pgid='pgtrigger_update_update_7faf3', table='Roles', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='role',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "authentication_roleevent" ("created_at", "created_by_id", "deleted_at", "description", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_code", "role_name", "updated_at", "updated_by_id") VALUES (OLD."created_at", OLD."created_by_id", OLD."deleted_at", OLD."description", OLD."id", OLD."is_active", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."role_code", OLD."role_name", OLD."updated_at", OLD."updated_by_id"); RETURN NULL;', hash='9e7cdcd3012623f3f1378c2c54d0d016ed3ba5dc', operation='DELETE', pgid='pgtrigger_delete_delete_4c50a', table='Roles', when='AFTER')),
        ),
        migrations.AddField(
            model_name='customuserevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='customuserevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduleregistryevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='moduleregistryevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='authentication.moduleregistry'),
        ),
        migrations.AddField(
            model_name='roleevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='roleevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='roleevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='authentication.role'),
        ),
        migrations.AddField(
            model_name='roleevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất'),
        ),
    ]
