# Generated by Django 5.2.17 on 2026-09-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuserevent_moduleregistryevent_roleevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='authentication.UserRole', through_fields=('user', 'role'), to='authentication.role', verbose_name='Các vai trò đảm nhiệm'),
        ),
    ]
