# Generated by Django 5.2.17 on 2026-09-29 15:27

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_roles'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='moduleregistry',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='moduleregistry',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='moduleregistry',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='moduleregistry',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả tiếng Anh'),
        ),
        migrations.AddField(
            model_name='moduleregistry',
            name='module_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên hiển thị tiếng Anh'),
        ),
        migrations.AddField(
            model_name='moduleregistryevent',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả tiếng Anh'),
        ),
        migrations.AddField(
            model_name='moduleregistryevent',
            name='module_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên hiển thị tiếng Anh'),
        ),
        migrations.AlterField(
            model_name='moduleregistry',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Khóa icon (constants/iconMap)'),
        ),
        migrations.AlterField(
            model_name='moduleregistryevent',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Khóa icon (constants/iconMap)'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='moduleregistry',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "authentication_moduleregistryevent" ("created_at", "description", "description_en", "icon", "id", "is_active", "is_navigation", "module_code", "module_name", "module_name_en", "parent_code", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "route_path", "sort_order", "updated_at") VALUES (NEW."created_at", NEW."description", NEW."description_en", NEW."icon", NEW."id", NEW."is_active", NEW."is_navigation", NEW."module_code", NEW."module_name", NEW."module_name_en", NEW."parent_code", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."route_path", NEW."sort_order", NEW."updated_at"); RETURN NULL;', hash='2c9089465dee0e91cd483381728c0f3e3643ec9d', operation='INSERT', pgid='pgtrigger_insert_insert_8a93c', table='ModuleRegistries', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='moduleregistry',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "authentication_moduleregistryevent" ("created_at", "description", "description_en", "icon", "id", "is_active", "is_navigation", "module_code", "module_name", "module_name_en", "parent_code", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "route_path", "sort_order", "updated_at") VALUES (NEW."created_at", NEW."description", NEW."description_en", NEW."icon", NEW."id", NEW."is_active", NEW."is_navigation", NEW."module_code", NEW."module_name", NEW."module_name_en", NEW."parent_code", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."route_path", NEW."sort_order", NEW."updated_at"); RETURN NULL;', hash='c7f1bb444594be3af8dac92976969c796348d2ab', operation='UPDATE', pgid='pgtrigger_update_update_005a8', table='ModuleRegistries', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='moduleregistry',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "authentication_moduleregistryevent" ("created_at", "description", "description_en", "icon", "id", "is_active", "is_navigation", "module_code", "module_name", "module_name_en", "parent_code", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "route_path", "sort_order", "updated_at") VALUES (OLD."created_at", OLD."description", OLD."description_en", OLD."icon", OLD."id", OLD."is_active", OLD."is_navigation", OLD."module_code", OLD."module_name", OLD."module_name_en", OLD."parent_code", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."route_path", OLD."sort_order", OLD."updated_at"); RETURN NULL;', hash='31295ec55fe1045aa22b87fc85c6fcad48f56831', operation='DELETE', pgid='pgtrigger_delete_delete_e42e5', table='ModuleRegistries', when='AFTER')),
        ),
    ]
